alibabacloud.ha.desc=Monitor your Alibaba Cloud services with their exclusive set of metrics that help you drill deep down into your resources.
huaweicloud_dds.mongo015_queues_readers=Queued Operations Waiting for Read Lock
huaweicloud_dds.mongo016_queues_writers=Queued Operations Waiting for Write Lock
huaweicloud_dds.mongo017_page_faults=Page Faults
huaweicloud_dds.mongo018_porfling_num=Slow Queries
huaweicloud_dds.mongo019_cursors_open=Maintained Cursors
huaweicloud_dds.mongo020_cursors_timeOut=Timeout Cursors
huaweicloud_dds.mongo021_wt_cahe_usage=Bytes in WiredTiger Cache
huaweicloud_dds.mongo022_wt_cahe_dirty=Tracked Dirty Bytes in WiredTiger Cache
huaweicloud_dds.mongo023_wInto_wtCache=Bytes Written Into Cache per Second
example.withhtml=This is text with <div>an inner div</div> and a link <a href="http://example.com">click here</a> that should keep tags.
