import re

def translate_text(text):
    """使用预定义字典进行翻译"""
    translations = {
        'Monitor your Alibaba Cloud services with their exclusive set of metrics that help you drill deep down into your resources.': '使用阿里云独有的指标集监控您的阿里云服务，帮助您深入了解您的资源。',
        'Simplify DigitalOcean cloud monitoring. Automatically track DigitalOcean services, diagnose slowdowns, and keep your systems running smoothly.': '简化DigitalOcean云监控。自动跟踪DigitalOcean服务，诊断减速，并保持您的系统平稳运行。',
        'Monitor your Akamai cloud infrastructure, assess performance constraints, and ensure rapid issue resolution across your cloud.': '监控您的Akamai云基础设施，评估性能约束，并确保云中的快速问题解决。',
        'Steps to generate AccessKey ID and AccessKey for monitoring': '生成AccessKey ID和AccessKey以进行监控的步骤',
        'Access Key Id': '访问密钥ID',
        'Access key secret': '访问密钥秘密',
        'This is the AccessKey ID generated from your Alibaba Cloud RAM console. Site24x7 uses it to authenticate API calls and retrieve resource metadata.': '这是从您的阿里云RAM控制台生成的AccessKey ID。Site24x7使用它来验证API调用并检索资源元数据。',
        'This is the AccessKey Secret paired with your AccessKey ID. Site24x7 uses it to securely access Alibaba Cloud APIs.': '这是与您的AccessKey ID配对的AccessKey Secret。Site24x7使用它来安全访问阿里云API。',
        'Steps to create OAuth Application for monitoring': '创建OAuth应用程序以进行监控的步骤',
        'Site24x7 OAuth Provider Id': 'Site24x7 OAuth提供商ID',
        'Provider name': '提供商名称',
        'Access Token': '访问令牌',
        'Steps to generate Access Token for monitoring': '生成访问令牌以进行监控的步骤',
        'Access Key ID': '访问密钥ID',
        'Secret Access Key': '秘密访问密钥',
        'This is the AccessKey ID generated from your Huawei Cloud IAM console. Site24x7 uses it to authenticate API calls and retrieve resource metadata.': '这是从您的华为云IAM控制台生成的AccessKey ID。Site24x7使用它来验证API调用并检索资源元数据。',
        'This is the Secret Access Key paired with your AccessKey ID. Site24x7 uses it to securely access Huawei Cloud APIs.': '这是与您的AccessKey ID配对的Secret Access Key。Site24x7使用它来安全访问华为云API。',
        'Resource Discovery Task Started Successfully': '资源发现任务已成功启动',
        'Resource Discovery Task is Running Already. Please try after sometime': '资源发现任务已在运行。请稍后重试',
        'View the resources listed under this Service Type. Click on any Resource monitor to view their performance metrics, meta data and more.': '查看此服务类型下列出的资源。点击任何资源监控器以查看其性能指标、元数据等。',
        'HuaweiCloud SFS': '华为云SFS',
        'SFS': 'SFS',
        'Add HuaweiCloud SFS Monitor': '添加华为云SFS监控器',
        'Edit HuaweiCloud SFS Monitor': '编辑华为云SFS监控器',
        'HuaweiCloud Scalable File Service Monitor': '华为云可扩展文件服务监控器',
        'Performance Metrics': '性能指标',
        'SFS Summary': 'SFS摘要',
        'Unit': '单位',
        'Read Bandwidth': '读取带宽',
        'Write Bandwidth': '写入带宽',
        'Read TPS': '读取TPS',
        'Write TPS': '写入TPS',
        'Standard Storage Usage': '标准存储使用量',
        'Infrequent Access Storage Usage': '不频繁访问存储使用量',
        'Read Write Bandwidth': '读写带宽',
        'Read Operations': '读取操作',
        'Write Operations': '写入操作',
        'Read Write Operations': '读写操作',
        'Used Capacity': '已用容量',
        'Throughput': '吞吐量',
        'Operations': '操作',
        'TPS': 'TPS',
        'Capacity': '容量',
        'Throughput Metrics': '吞吐量指标',
        'TPS Metrics': 'TPS指标',
        'Operations Metrics': '操作指标',
        'Capacity Metrics': '容量指标',
        'Average': '平均',
        'Avg': '平均',
        'Max': '最大',
        'Min': '最小',
        'HuaweiCloud SFS Turbo': '华为云SFS Turbo',
        'SFS Turbo': 'SFS Turbo',
        'Add HuaweiCloud SFS Turbo Monitor': '添加华为云SFS Turbo监控器',
        'Edit HuaweiCloud SFS Turbo Monitor': '编辑华为云SFS Turbo监控器',
        '1. In DigitalOcean, navigate to ': '1. 在DigitalOcean中，导航到 ',
        ' > ': ' > ',
        'OAuth Applications': 'OAuth应用程序',
        'Register Application': '注册应用程序',
        '.': '。',
        '2. Save and securely store the Client ID and Client Secret.': '2. 保存并安全存储客户端ID和客户端密钥。',
        '3. In Site24x7, navigate to ': '3. 在Site24x7中，导航到 ',
        'Admin': '管理员',
        'Configuration Profiles': '配置配置文件',
        'OAuth Providers': 'OAuth提供商',
        'Add Provider': '添加提供商',
        '.': '。',
        '4. Use Authorization Code Flow and set endpoints: i. ': '4. 使用授权代码流并设置端点：i. ',
        'Authorization': '授权',
        '  ii.  ': '  ii.  ',
        'Token': '令牌',
        '5. Enter Client ID, Secret, and Redirect URI and then authorize to generate the access token and validate configuration.': '5. 输入客户端ID、密钥和重定向URI，然后授权生成访问令牌并验证配置。',
        '1. Sign in to ': '1. 登录到 ',
        'DigitalOcean console': 'DigitalOcean控制台',
        ' ': ' ',
        '2. Go to ': '2. 转到 ',
        'API Settings': 'API设置',
        'Left panel': '左侧面板',
        'API': 'API',
        'Tokens': '令牌',
        'Generate New Token': '生成新令牌',
        '3. Create ': '3. 创建 ',
        'Personal Access Token': '个人访问令牌',
        ' (PAT)': ' (PAT)',
        '4. Ensure all prerequisites are met: ': '4. 确保满足所有先决条件： ',
        '(a) Provide ': '(a) 提供 ',
        'Read': '读取',
        ' permission (sufficient for monitoring). ': ' 权限（足以进行监控）。 ',
        '(b) DigitalOcean account with Resource Viewer permissions. ': '(b) 具有资源查看器权限的DigitalOcean账户。 ',
        '(c) API access enabled. ': '(c) API访问已启用。 ',
        '(d)Access to DigitalOcean Control Panel or Developer API': '(d)访问DigitalOcean控制面板或开发者API',
        '5. Click ': '5. 点击 ',
        'Generate Token': '生成令牌',
        ' IMPORTANT: Copy and store the token securely. It cannot be viewed again. ': ' 重要：安全复制并存储令牌。它无法再次查看。 ',
        '1. Login to ': '1. 登录到 ',
        'Akamai Cloud console': 'Akamai云控制台',
        ' and navigate to ': ' 并导航到 ',
        'Resource Access Manangement (RAM) console': '资源访问管理(RAM)控制台',
        '2. In the Left menu, navigate to  Users -> Create Users to create a separate user for Site24x7 in  Alibaba cloud console': '2. 在左侧菜单中，导航到用户 -> 创建用户，以在阿里巴巴云控制台中为Site24x7创建一个单独的用户',
        '3. Create AccessKey by enabling the Permanent AccessKey': '3. 通过启用永久AccessKey创建AccessKey',
        '4. Download the AccessKey and save the user': '4. 下载AccessKey并保存用户',
        '5. Use that Access Key ID and Access key secret while creating an Alibaba monitor below': '5. 在下面创建阿里巴巴监控器时使用该访问密钥ID和访问密钥秘密',
        'Akamai Cloud Manager': 'Akamai云管理器',
        '2. Go to ': '2. 转到 ',
        'Profile icon': '配置文件图标',
        'API Tokens': 'API令牌',
        'Create Personal Access Token': '创建个人访问令牌',
        '.': '。',
        '3. Name the token (e.g., site24x7-monitoring).': '3. 命名令牌（例如，site24x7-monitoring）。',
        '4. Enable API access for the user and under Access Scopes, enable Read access for: ': '4. 为用户启用API访问，并在访问范围下，为以下启用读取访问： ',
        'Linodes (Compute Instances), NodeBalancers (Load Balancers)': 'Linodes（计算实例）、NodeBalancers（负载均衡器）',
        '5. Click Create Token and copy it securely.': '5. 点击创建令牌并安全复制。',
        'IMPORTANT': '重要',
        ': Read-only access is sufficient for monitoring. Store your PAT securely; it cannot be retrieved once generated.': '：只读访问足以进行监控。安全存储您的PAT；一旦生成就无法检索。',
        '1. Log in to Huawei ': '1. 登录到华为 ',
        'Identity and Access Management (IAM)': '身份和访问管理(IAM)',
        ' console.': ' 控制台。',
        '2. In the left menu, navigate to ': '2. 在左侧菜单中，导航到 ',
        'Users >': '用户 >',
        ' Click ': ' 点击 ',
        'Create User': '创建用户',
        ' to create a separate user for Site24x7.': ' 以创建Site24x7的单独用户。',
        '3. Click the newly created username. Under the Access Keys section, click on the ': '3. 点击新创建的用户名。在访问密钥部分，点击 ',
        'Create Access Key': '创建访问密钥',
        ' button.': ' 按钮。',
        '4. A pop-up opens with recommendations; check the box to generate the access key. Click ': '4. 弹出窗口打开并显示建议；选中复选框以生成访问密钥。点击 ',
        'Next': '下一步',
        '.': '。',
        '5. Enter your description, click ': '5. 输入您的描述，点击 ',
        'OK': '确定',
        '.': '。',
        '6. Click ': '6. 点击 ',
        'Download': '下载',
        ' to save the Credentials CSV file containing the ': ' 以保存包含 ',
        'Access Key Id': '访问密钥ID',
        ' and ': ' 和 ',
        'Secret Access Key': '秘密访问密钥',
        ' for use in the Huawei Cloud monitor.': ' 以在华为云监控器中使用。',
        '1. Log in to the': '1. 登录到',
        ' (RAM) console in Alibaba.': ' (RAM)控制台在阿里巴巴。',
        '2. In the left menu, navigate to': '2. 在左侧菜单中，导航到',
        ' > choose': ' > 选择',
        ' to create a separate user for Site24x7 in the Alibaba Cloud console.': ' 以在阿里巴巴云控制台中为Site24x7创建一个单独的用户。',
        '3. Provide the': '3. 提供',
        'Logon Name': '登录名',
        ' and': ' 和',
        'Display Name': '显示名称',
        ', and enable': '，并启用',
        'Using permanent AccessKey to access': '使用永久AccessKey访问',
        '.': '。',
        '4. After authenticating with the MFA verification, click': '4. 使用MFA验证进行身份验证后，点击',
        'OK': '确定',
        ' in the': ' 在',
        'Save AccessKey Pair': '保存AccessKey对',
        ' pop-up.': ' 弹出窗口。',
        '5. Click': '5. 点击',
        'Download CSV': '下载CSV',
        ' and save the file.': ' 并保存文件。',
        '6. Provide the saved': '6. 提供保存的',
        'AccessKey ID': 'AccessKey ID',
        ' and': ' 和',
        'AccessKey Secret': 'AccessKey Secret',
        ' while creating an Alibaba Cloud monitor.': ' 在创建阿里巴巴云监控器时。',
        '1. In DigitalOcean, navigate to': '1. 在DigitalOcean中，导航到',
        'API': 'API',
        ' >': ' >',
        'OAuth Applications': 'OAuth应用程序',
        ' >': ' >',
        'Register Application': '注册应用程序',
        '.': '。',
        '2. Save and securely store the Client ID and Client Secret.': '2. 保存并安全存储客户端ID和客户端密钥。',
        '3. In Site24x7, navigate to': '3. 在Site24x7中，导航到',
        'Admin': '管理员',
        ' >': ' >',
        'Configuration Profiles': '配置配置文件',
        ' >': ' >',
        'OAuth Providers': 'OAuth提供商',
        ' >': ' >',
        'Add Provider': '添加提供商',
        '.': '。',
        '4. Use Authorization Code Flow and set endpoints: i.': '4. 使用授权代码流并设置端点：i.',
        'Authorization': '授权',
        '  ii.': '  ii.',
        'Token': '令牌',
        '5. Enter Client ID, Secret, and Redirect URI and then authorize to generate the access token and validate configuration.': '5. 输入客户端ID、密钥和重定向URI，然后授权生成访问令牌并验证配置。',
        '1. Sign in to': '1. 登录到',
        'DigitalOcean console': 'DigitalOcean控制台',
        ' ': ' ',
        '2. Go to': '2. 转到',
        'API Settings': 'API设置',
        ' >': ' >',
        'Left panel': '左侧面板',
        ' >': ' >',
        'API': 'API',
        ' >': ' >',
        'Tokens': '令牌',
        ' >': ' >',
        'Generate New Token': '生成新令牌',
        '3. Create': '3. 创建',
        'Personal Access Token': '个人访问令牌',
        ' (PAT)': ' (PAT)',
        '4. Ensure all prerequisites are met:': '4. 确保满足所有先决条件：',
        '(a) Provide': '(a) 提供',
        'Read': '读取',
        ' permission (sufficient for monitoring).': ' 权限（足以进行监控）。',
        '(b) DigitalOcean account with Resource Viewer permissions.': '(b) 具有资源查看器权限的DigitalOcean账户。',
        '(c) API access enabled.': '(c) API访问已启用。',
        '(d)Access to DigitalOcean Control Panel or Developer API': '(d)访问DigitalOcean控制面板或开发者API',
        '5. Click': '5. 点击',
        'Generate Token': '生成令牌',
        ' IMPORTANT: Copy and store the token securely. It cannot be viewed again.': ' 重要：安全复制并存储令牌。它无法再次查看。',
        '1. Login to': '1. 登录到',
        'Akamai Cloud console': 'Akamai云控制台',
        ' and navigate to': ' 并导航到',
        'Resource Access Manangement (RAM) console': '资源访问管理(RAM)控制台',
        '2. In the Left menu, navigate to  Users -> Create Users to create a separate user for Site24x7 in  Alibaba cloud console': '2. 在左侧菜单中，导航到用户 -> 创建用户，以在阿里巴巴云控制台中为Site24x7创建一个单独的用户',
        '3. Create AccessKey by enabling the Permanent AccessKey': '3. 通过启用永久AccessKey创建AccessKey',
        '4. Download the AccessKey and save the user': '4. 下载AccessKey并保存用户',
        '5. Use that Access Key ID and Access key secret while creating an Alibaba monitor below': '5. 在下面创建阿里巴巴监控器时使用该访问密钥ID和访问密钥秘密',
        '1. Login to': '1. 登录到',
        'Akamai Cloud Manager': 'Akamai云管理器',
        '2. Go to': '2. 转到',
        'Profile icon': '配置文件图标',
        ' >': ' >',
        'API Tokens': 'API令牌',
        ' >': ' >',
        'Create Personal Access Token': '创建个人访问令牌',
        '.': '。',
        '3. Name the token (e.g., site24x7-monitoring).': '3. 命名令牌（例如，site24x7-monitoring）。',
        '4. Enable API access for the user and under Access Scopes, enable Read access for:': '4. 为用户启用API访问，并在访问范围下，为以下启用读取访问：',
        'Linodes (Compute Instances), NodeBalancers (Load Balancers)': 'Linodes（计算实例）、NodeBalancers（负载均衡器）',
        '5. Click Create Token and copy it securely.': '5. 点击创建令牌并安全复制。',
        'IMPORTANT': '重要',
        ': Read-only access is sufficient for monitoring. Store your PAT securely; it cannot be retrieved once generated.': '：只读访问足以进行监控。安全存储您的PAT；一旦生成就无法检索。',
        '1. Log in to Huawei': '1. 登录到华为',
        'Identity and Access Management (IAM)': '身份和访问管理(IAM)',
        ' console.': ' 控制台。',
        '2. In the left menu, navigate to': '2. 在左侧菜单中，导航到',
        'Users >': '用户 >',
        ' Click': ' 点击',
        'Create User': '创建用户',
        ' to create a separate user for Site24x7.': ' 以创建Site24x7的单独用户。',
        '3. Click the newly created username. Under the Access Keys section, click on the': '3. 点击新创建的用户名。在访问密钥部分，点击',
        'Create Access Key': '创建访问密钥',
        ' button.': ' 按钮。',
        '4. A pop-up opens with recommendations; check the box to generate the access key. Click': '4. 弹出窗口打开并显示建议；选中复选框以生成访问密钥。点击',
        'Next': '下一步',
        '.': '。',
        '5. Enter your description, click': '5. 输入您的描述，点击',
        'OK': '确定',
        '.': '。',
        '6. Click': '6. 点击',
        'Download': '下载',
        ' to save the Credentials CSV file containing the': ' 以保存包含',
        'Access Key Id': '访问密钥ID',
        ' and': ' 和',
        'Secret Access Key': '秘密访问密钥',
        ' for use in the Huawei Cloud monitor.': ' 以在华为云监控器中使用。',
        '7. Provide the saved': '7. 提供保存的',
        ' while creating a Huawei Cloud monitor.': ' 在创建华为云监控器时。',
        'Instance Inbound Bytes': '实例入站字节',
        'Instance Outbound Bytes': '实例出站字节',
        'Instance Inbound Bits Rate': '实例入站比特率',
        'Instance Outbound Bits Rate': '实例出站比特率',
        'Instance Inbound Packets': '实例入站数据包',
        'Instance Outbound Packets': '实例出站数据包',
        'Instance Blackhole Dropped Packets': '实例黑洞丢弃数据包',
        'Instance No-Route Dropped Packets': '实例无路由丢弃数据包',
        'Attachment Inbound Bytes': '附件入站字节',
        'Attachment Outbound Bytes': '附件出站字节',
        'Attachment Inbound Bits Rate': '附件入站比特率',
        'Attachment Outbound Bits Rate': '附件出站比特率',
        'Attachment Inbound Packets': '附件入站数据包',
        'Attachment Outbound Packets': '附件出站数据包',
        'Attachment Blackhole Dropped Packets': '附件黑洞丢弃数据包',
        'Attachment No-Route Dropped Packets': '附件无路由丢弃数据包',
        'SFS': 'SFS',
        'TPS': 'TPS',
        'SFS Turbo': 'SFS Turbo',
        'HuaweiCloud SFS Turbo File System Monitor': '华为云SFS Turbo文件系统监控器',
        'SFS Turbo Summary': 'SFS Turbo摘要',
        'Data Read IO Bytes': '数据读取IO字节',
        'Data Write IO Bytes': '数据写入IO字节',
        'Total IO Bytes': '总IO字节',
        'Metadata IO Bytes': '元数据IO字节',
        'IOPS': 'IOPS',
        'Client Connections': '客户端连接',
        'Used Capacity Percent': '已用容量百分比',
        'Used Inode': '已用Inode',
        'Used Inode Percent': '已用Inode百分比',
        'IOPS & Connections': 'IOPS和连接',
        'Capacity & Inodes': '容量和Inodes',
        'HuaweiCloud CBR': '华为云CBR',
        'CBR': 'CBR',
        'Add HuaweiCloud CBR Monitor': '添加华为云CBR监控器',
        'Edit HuaweiCloud CBR Monitor': '编辑华为云CBR监控器',
        'HuaweiCloud Cloud Backup and Recovery Monitor': '华为云云备份和恢复监控器',
        'CBR Summary': 'CBR摘要',
        'Vault Utilization': '保险库利用率',
        'Used Vault Size': '已用保险库大小',
        'Backup': '备份',
        'HuaweiCloud RDS MySQL': '华为云RDS MySQL',
        'RDS MySQL': 'RDS MySQL',
        'Add HuaweiCloud RDS MySQL Monitor': '添加华为云RDS MySQL监控器',
        'Edit HuaweiCloud RDS MySQL Monitor': '编辑华为云RDS MySQL监控器',
        'HuaweiCloud RDS MySQL Monitor': '华为云RDS MySQL监控器',
        'RDS MySQL Summary': 'RDS MySQL摘要',
        'CPU Utilization': 'CPU利用率',
        'Memory Utilization': '内存利用率',
        'Network Input Throughput': '网络输入吞吐量',
        'Network Output Throughput': '网络输出吞吐量',
        'Total Connections': '总连接数',
        'Active Connections': '活动连接数',
        'Queries Per Second': '每秒查询数',
        'Transactions Per Second': '每秒事务数',
        'InnoDB Buffer Pool Utilization': 'InnoDB缓冲池利用率',
        'InnoDB Buffer Pool Hit Rate': 'InnoDB缓冲池命中率',
        'InnoDB Buffer Pool Dirty Page Rate': 'InnoDB缓冲池脏页率',
        'InnoDB Read Throughput': 'InnoDB读取吞吐量',
        'InnoDB Write Throughput': 'InnoDB写入吞吐量',
        'InnoDB Read Operations': 'InnoDB读取操作',
        'InnoDB Write Operations': 'InnoDB写入操作',
        'Delete Statements': '删除语句',
        'Insert Statements': '插入语句',
        'Select Statements': '选择语句'
    }
    return translations.get(text.strip(), text)

def extract_and_translate(text):
    """提取HTML标签外的文本进行翻译"""
    # 检查是否包含HTML标签
    if '<' in text and '>' in text:
        # 使用正则表达式找到HTML标签和纯文本
        parts = re.split(r'(<[^>]+>)', text)
        translated_parts = []
        for part in parts:
            if re.match(r'<[^>]+>', part):
                # HTML标签，保持不变
                translated_parts.append(part)
            else:
                # 纯文本，翻译
                translated_parts.append(translate_text(part))
        return ''.join(translated_parts)
    else:
        # 没有HTML标签，整个翻译
        return translate_text(text)

def process_file(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    with open(output_file, 'w', encoding='utf-8') as f:
        for line in lines:
            if '=' in line:
                key, value = line.split('=', 1)
                translated_value = extract_and_translate(value.strip())
                f.write(f"{key}={translated_value}\n")
            else:
                f.write(line)

if __name__ == "__main__":
    input_file = r"d:\Zoho\vscode\Translate\new-huawei-keys.txt"
    output_file = r"d:\Zoho\vscode\Translate\translated_output.txt"
    process_file(input_file, output_file)
    print("Translation completed. Output saved to translated_output.txt")